# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function computes the exponential of a matrix.
#' @title Compute the exponential of a matrix
#' @param x An numeric matrix
#' @return A numeric matrix
#' @seealso The \pkg{expm} package and its documentation.
expm_rcpp <- function(x) {
    .Call(`_CallExpmDemo_expm_rcpp`, x)
}

